[target.aarch64-pc-windows-msvc]
linker = "aarch64-w64-mingw32-clang"
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
